### ISSUE TITLE
Proposed outline of the paper

### ISSUE THREAD

**Issue by rickyyx** [cs3235-autoauth/report#1]
Hi all,

(Assuming we have not started thinking about this?? This is the first deliverable tho I believe, due in less than 2 wks..... 😢 )

the dumb proposed outline (feel free to change and suggest better ideas) I have for the skeleton file goes as below: 

- Intro: simple intro [assigned to @?? ] 
  - background: traditional user identify methods
  - motivation : why fingerprinting is now a thing?
  - into of fingerprint tech : the history, the enabled factors,....
- related work : a survey of other papers 
- fingerprint tech
  - Mechanism: How it works 
  - Ecosystem: what has been built, some applications usages. 
  - classification: some categories 
  - Auth
    - how auth is done, and how fingerprint can be used to augment auth
    - desired properties: some important things to consider for auth with fingerprint
    - thread model: what can go wrong 
- Plugin : we built a plugin 
   - Design 
   - Implementation 
- Extension: what else to talk about? 
- Conclusion: we learned a lot! 

Once we have the outline sorted out, I think we should break it into parts so that each person work on one portion. 

@cs3235-autoauth/developers

**Comment by KeithSOC** [comment]
I volunteer to cover the `plugin` section!

**Comment by Xenonym** [comment]
I can do the intro and related work!

**Comment by Xenonym** [comment]
[Keith's section](https://docs.google.com/document/d/11-qRkRf111jDyuUkkF1appvfN-vB1Xsz4bdVoEG0jYU/edit)

**Comment by KeithSOC** [comment]
![flow](https://user-images.githubusercontent.com/2218315/48250681-17015700-e43a-11e8-8c04-e0d0c858b681.png)

**Comment by KeithSOC** [comment]
![ss](https://user-images.githubusercontent.com/2218315/48250687-1c5ea180-e43a-11e8-82cd-db9188501475.PNG)

**Comment by KeithSOC** [comment]
@cs3235-autoauth/developers 

Current outline as follows; require any changes?

Abstract

1. Introduction
- Background
- What is device fingerprinting

2. Fingerprint Technology
- Overview of Fingerprinting Techniques
- Survey of Fingerprinting Techniques
- Fingerprinting for Authentication

3. Fingerprint Auth Plugin
- Device Fingerprint Plugin
- Demo Web Application

4. Extensions
- Improvements to be made

5. Conclusion

6. References

**Comment by AngWM** [comment]
I've added another subsection within the extensions
